# Blog
keywords: mutronic,HTML,CSS,android,Linux
author: Gabriel Rosser,grosser@crimson.ua.edu
description: Nothing lasts forever.
avatar: /images/favicon.png

# Social Accounts
twitter: 
rss: 
weibo: 
instagram: 
github: 
facebook: 

# Comment
duoshuo: 
disqus: 
gentie: 
